<?php
/**
 * @file
 */

/**
 * class
  $FetchRules = new FetchRules();
  $FetchRules->divArea();
 */
class FetchRules {
  /**
   * tid = 2,
   * @return, tids array
   */
  public function divArea() {
    $output = '<div class="Program_guide">.*</div></div>';
    return $output;
  }

  /** - - - - - - content - - - - - - - - - - - - - - - - - - - - - - - - - -  */
  /**
   * tid = 2,
   * @return, tids array
   */
  public function guangXiContent() {

  }
}
